### PR TITLE
Update Vietnamese translation

### PR DESCRIPTION
**Pull request by ghost**
Fix grammar related issues

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Vietnamese has accents, which can cause issue in translation lol

**Comment by ghost** [comment]
@asterixiverz check pr sir pls

**Comment by ghost** [comment]
"Maybe no one cares" closing 🌀💤

**Comment by asterixiverz** [comment]
why you close the pr @Kinnara-icz ?

**Comment by ghost** [comment]
> why you close the pr @Kinnara-icz ?

:spin:

**Comment by ghost** [comment]
uhh commit conflict

**Pull request closed without merging**
